---
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: logging
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  version: "2.9.10"
  targetNamespace: logging
  valuesContent: |-
    loki:
      auth_enabled: false
      persistence:
        enabled: true
        size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
    promtail:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_label_release]
            target_label: release
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
