---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: "45.7.1"
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      adminPassword: prom-operator  # Change this in production
      persistence:
        enabled: true
        size: 1Gi
    prometheus:
      prometheusSpec:
        retention: 24h  # Adjust retention based on your needs
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 512Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    nodeExporter:
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 20m
          memory: 32Mi

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
  - port: metrics  # Your app should expose metrics on this port
    interval: 30s
